Added function lsinc()

diff --git a/run-backup b/run-backup
--- a/run-backup
+++ b/run-backup
@@ -66,6 +66,54 @@ helpmsg()
 	EOF
 }
 
+lsinc()
+{
+    # Returns a numbered listing of past backup increments
+    #
+    # Arguments:
+    #   Absolute path to destination (default: none)
+    #   Absolute path to temporary directory (default: none)
+    #
+    # Return values:
+    #   Listing of backup increments
+    if [ "$#" -ne 2 ]
+    then
+        exit 1
+    fi
+
+    YYYY='[[:digit:]]\{4\}'
+    MM='[[:digit:]]\{2\}'
+    MMM='[[:alpha:]]\{3\}'
+    DD='[[:digit:]]\{2\}'
+    ddd='[[:alpha:]]\{3\}'
+    hh='[[:digit:]]\{2\}'
+    mm='[[:digit:]]\{2\}'
+    ss='[[:digit:]]\{2\}'
+    fmtlabel="${ddd} ${MMM} ${DD} ${hh}:${mm}:${ss} ${YYYY}"
+    fmttimestamp="${YYYY}-${MM}-${DD}T${hh}:${mm}:${ss}[+-]${hh}:${mm}"
+
+    input="$(rdiff-backup --list-increments "$1")"
+    current="$(printf "$input" | tail -n 1 | sed -n "s/^.*\(${fmtlabel}\).*$/\\1/p")"
+    previous="$(printf "$input" | head -n -1 | tail -n +2 | sed '1!G;h;$!d')"
+
+    printf "Most recent backup:\n\t%s\n" "$current"
+    printf "Previous backups:\n"
+
+    i=1
+    printf "%s\n" "$previous" | while read line
+    do
+        label="$(printf "$line" | sed -n "s/^.*\(${fmtlabel}\).*$/\\1/p")"
+        timestamp="$(printf "$line" | sed -n "s/^.*\(${fmttimestamp}\).*$/\\1/p")"
+
+        printf "  %s\t" "$i"
+        mkdir "${2}/$i"
+        printf "%s\n" "$label" | tee "${2}/${i}/label"
+        printf "$timestamp" >"${2}/${i}/timestamp" 2>&1
+
+        i=$(($i+1))
+    done
+}
+
 mktempdir()
 {
     # Creates a temporary directory in TMPDIR
